# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20170103_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='earnings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='placement',
            name='earnings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
