# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0002_auto_20170119_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='advertising_budget',
            new_name='advertising_burn',
        ),
        migrations.AddField(
            model_name='profile',
            name='advertising_funds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='publisher_payout',
            field=models.FloatField(default=0),
        ),
    ]
