# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0003_auto_20170227_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedUser',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SIGNED_UP', 'SIGNED_UP'), ('EMAILED', 'EMAILED'), ('REGISTERED', 'REGISTERED'), ('CONVERTED', 'CONVERTED')], default='SIGNED_UP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
