# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0009_auto_20170407_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
