# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0010_auto_20170410_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
