# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0012_payments_payouts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Payouts',
            new_name='Payout',
        ),
    ]
