# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chym_user', '0013_auto_20170419_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='advertising_funds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='publisher_payout',
            field=models.IntegerField(default=0),
        ),
    ]
