# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creative_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Adgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('total_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Hmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Targeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Device')),
                ('hmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Hmd')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Os'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.CampaignType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Pricing'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Budget'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Campaign'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='targeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Targeting'),
        ),
        migrations.AddField(
            model_name='ad',
            name='adgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Adgroup'),
        ),
    ]
