# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pricing', models.CharField(choices=[('CPM', 'CPM')], default='CPM', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IMG_360', 'IMG_360'), ('VIDEO_360', 'VIDEO_360')], max_length=20)),
                ('total_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('os', models.CharField(choices=[('ANDROID', 'ANDROID')], default='ANDROID', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Targeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmd', models.CharField(choices=[('GEAR_VR', 'GEAR_VR'), ('DAYDREAM', 'DAYDREAM')], default='GEAR_VR', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Device')),
            ],
        ),
        migrations.AddField(
            model_name='adgroup',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Budget'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Campaign'),
        ),
    ]
