# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:36
from __future__ import unicode_literals

from django.db import migrations


def load_campaign_type(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    CampaignType = apps.get_model("advertiser", "CampaignType")
    CampaignType.objects.using(db_alias).bulk_create([
        CampaignType(id=1, name="Image 360"),
        CampaignType(id=2, name="Video 360"),
    ])


def load_os(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    Os = apps.get_model("advertiser", "Os")
    Os.objects.using(db_alias).bulk_create([
        Os(id=1, name="Android", version=0),
    ])


def load_pricing(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    Pricing = apps.get_model("advertiser", "Pricing")
    Pricing.objects.using(db_alias).bulk_create([
        Pricing(id=1, name="CPC"),
        Pricing(id=2, name="CPM"),
    ])


def load_hmd(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    Hmd = apps.get_model("advertiser", "Hmd")
    Hmd.objects.using(db_alias).bulk_create([
        Hmd(id=1, name="Gear VR"),
        Hmd(id=2, name="Cardboard"),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_campaign_type),
        migrations.RunPython(load_os),
        migrations.RunPython(load_pricing),
        migrations.RunPython(load_hmd),
    ]
