# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='targeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Targeting'),
        ),
    ]
