# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_auto_20170103_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
