# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 03:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0003_auto_20170107_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroup',
            name='burn',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='burn',
        ),
        migrations.AddField(
            model_name='adgroup',
            name='todayBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adgroup',
            name='totalBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='todayBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='totalBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
