# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0004_auto_20170116_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='burn',
        ),
        migrations.AddField(
            model_name='ad',
            name='todayBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='ad',
            name='totalBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='todayBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='totalBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='todayBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='totalBurn',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
