# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0005_auto_20170209_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='landingPage',
            field=models.CharField(default='chymera.com', max_length=1000),
            preserve_default=False,
        ),
    ]
