# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_ad_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='appName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='appUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
