# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0007_auto_20170222_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='adType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
