# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0009_auto_20170417_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='hmd',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Hmd'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='os',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Os'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ram',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
